name: slither Analyze

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - '*'

jobs:
  slither-analyze:
    name: Slither Analyze
    runs-on: ubuntu-latest
    permissions:
      actions: read
      contents: read
      security-events: write
    steps:
      - name: Checkout repository and submodules
        uses: actions/checkout@v4
        with:
          submodules: recursive

      # The compile step used by the slither-action below is broken to this issue properly
      # using the 'target' directory: https://github.com/crytic/crytic-compile/issues/509
      # As a workaround until the issue is fixed, compile the contracts manually before
      # running the slither action, and then pass hte 'ignore-compile' flag to the slither action.
      - name: Compile Contracts
        run: |
          BASE_DIR=${XDG_CONFIG_HOME:-$HOME}
          curl -L https://foundry.paradigm.xyz | bash
          source $HOME/.bashrc
          $BASE_DIR/.foundry/bin/foundryup
          cd contracts/
          $BASE_DIR/.foundry/bin/forge build --force

      - name: Run Slither
        uses: crytic/slither-action@v0.3.0
        id: slither
        with:
          slither-config: "contracts/slither.config.json"
          target: "contracts/"
          ignore-compile: true
          sarif: results.sarif
          fail-on: none

      - name: Upload SARIF file
        uses: github/codeql-action/upload-sarif@v2
        with:
          sarif_file: ${{ steps.slither.outputs.sarif }}
