name: slither Analyze

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - "*"

jobs:
  slither-analyze:
    name: Slither Analyze
    runs-on: ubuntu-latest
    permissions:
      actions: read
      contents: read
      security-events: write
    steps:
      - name: Checkout repository and submodules
        uses: actions/checkout@v4
        with:
          submodules: recursive

      - name: Setup Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.8

      - name: Install Slither and Forge
        run: |
          pip install slither-analyzer
          curl -L https://foundry.paradigm.xyz | bash

      - name: Run Slither
        run: slither contracts/ --sarif contracts/results.sarif

      - name: Upload SARIF file
        uses: github/codeql-action/upload-sarif@v2
        with:
          sarif_file: contracts/results.sarif
